[package]
name = "my-bindicator"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Window", 
    "Document", 
    "HtmlElement",
    "HtmlFormElement",
    "MediaQueryList",
    "FormData",
    "EventTarget"
] }
gloo = "0.11"
gloo-net = { version = "0.6", features = ["http"] }
gloo-console = "0.3"
gloo-timers = { version = "0.3", features = ["futures"] }
gloo-storage = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["wasmbind"] }
quick-xml = "0.36"
yew-hooks = "0.3"
futures = "0.3"
futures-util = "0.3"
charming = "0.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
